<div id="ajax-example" data-bind="scope:'ajaxexample'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#ajax-example": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ajaxexample": {
                        "component": "Tha_Call/js/nan/ajax-example"
                    }
                }
            }
        }
    }
    </script>
</div>