<p style="color: royalblue;">noi dung trong the p</p>

<!-- <div data-bind="scope: 'component-name'">First name:
<div><input type="text" data-bind="textInput: firstName" /></div>
</div>
<p>Notes: Magento_Ui/js/core/app - this js is responsible for binding Knockout JS components with the DOM elements then you can use ko methods. 
    Scope attribute - it is used to chain the JS and the HTML DOM together using the knockoutjs. Component-name - Must be unique on the current page. 
    It can be any meaningful word and could be js file name. Use same name used in the
</p> -->


<script type="text/x-magento-init">
{
   "*": {
       "Tha_Call/js/myfile": {nan: "123123123"}
   }
}
</script>

<h4>noi dung trong h4</h4>