<div data-bind="scope: 'component-name'">First name:
<div><input type="text" data-bind="textInput: firstName" /></div>
</div>
<p>Notes: Magento_Ui/js/core/app - this js is responsible for binding Knockout JS components with the DOM elements then you can use ko methods. 
    Scope attribute - it is used to chain the JS and the HTML DOM together using the knockoutjs. 
    Component-name - Must be unique on the current page. I
    t can be any meaningful word and could be js file name. Use same name used in the
</p>